dist: xenial

language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "ceraalex99"
    token:
      secure: "QETSGYohorGSMJc2z9atvveLlAp+ljCIbxNUO9nIb36O/pbUck6x1COfqI6THlk0pwgmlC53XQG7tD0TdKr9vydNAIH4K+ywJeuX0ftuQuVStXABYHVAO3qiD7WDbXoVHjb+bSLc1JiGHrzQd1E45m3Y72u4fPFzmV6D5c/e/7dNutIY4p8lc1zhcbSpNlWjcicJ1WAfrazj0A2FlIaSrMLQuPNm4giL5+7Uv6v/e6/rB8qlX6RtniyQP4bHf6ui0caX0VDLNAeLZ/8/cY6IZc6eXQQxA1H4hkbcBOMuwv48uDP4GhXDdwxW5mGT8YSW8yYajvfmuQZxqi0JnmHMf63Lcdo5jpYeel0T9G3XaNgyZFisCyl3ctst9UQCOuk+8NVYgGF+FowEcVQvuG6PUhUiIFJ4vGR4KHfrfqXFbV0bqoRnbzmBSq11IYDXnH7SleJj072DWdFqTsEvRMfCVhurJiTnf/ihFD6paoxN/FGTDdqCPgr6Li+Fz8bLtMe4zQiUd1UTz2fqIGHgHW6BMr1AlRY3XoB6EYdFIN8WWnphYRSM1+ZzLH0LzhmF1o0JAZWyjNGHDp10/DsgXMsSmsNtGqIM4hSz/63mLkY7WvWiSM8u7HRlyswHTolp+6whIOt7gFNNxss3sizxIg3u8sFsD+Sla4x4yxivszY758U="

env:
  secure: "avNK7U6XdS7EKaJzmHrBaa1Ye52/5VV/EQi3sD7PGakseijvdjuIXpo2DGP8m5I5W0o4HCpBpjs+wd9gihEEkXOhwfg7+RygBWGSxzU/C9g9chJ0/SODmURY73S1XQc85GEGCVVudymBp6oDDw4c1QC+yQpi1lurr8w0n/BCuyTjMqMssPVfOltK9pD/Wy2SjtAGRMMe3YHxIEclAC0PH8eLjrPQV52CXg2hjiK4zneXNBm6IRSnKYAVJJ2dhDstNggptxqH/2MtYe44AHINn1gEdYJ0j6ERxKtY5Mi/3RJHFmNvZGW7l85QeNvnEKEMlidwyr+KmZ+F2wvXzE+v4ORdZz+izx1ejSkMqA2tEnPV23WWwMPMgP+jjFyNlPgHa3GxcZ0CADkUbGIp09Kbl0IMAN9PfM3q7H+qkpCVZ5/Q/ml3XXXote0+p2FAKUI4EL8R5lzmQkft+DnPLniUMbsfPVWjTruvQVNHY1Lgvf8ztWTtkLrgqH3i8tetvIqRq/yrVmchwmS1URxzBAEnGqIjTV5h5q8jrjwWei+qwURqTD2tXMoQxAIRng6rMIiEGhMA04gcxLMeaxGq+DQ/yLpR8+O8aFz8+2ISrz9DPUR9S5nLPzUv7RLOeHuuHerAZA10EfQK3pMH7KYvGDy71l7bIu6RcoyfyetPh6fnxLE="


script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ceraalex99_Pet_and_Go

after_success:
  - chmod a+x automerge
  - BRANCHES_TO_MERGE_REGEX='staging' BRANCH_TO_MERGE_INTO=develop GITHUB_REPO=ceraalex99/Pet_and_Go ./automerge